### ISSUE TITLE
Description missing for the -s argument

### ISSUE THREAD

**Issue by HankiDesign** [alexMyG/AndroPyTool#1]
The `-s` argument description is duplicated from the `-all` description above so now there's no instructions on how the flag should be used.

`-s SOURCE_FOLDER`,` --source SOURCE_FOLDER`: **Executes all steps of AndroPyTool (Recommended). In order to obtain a VirusTotal report, the argument -vt must be also provided followed by a VirusTotal API key. If the -all option is not provided, then only the last step is executed plus the provided arguments.**

**Comment by alexMyG** [comment]
Thanks! I have just updated the README file.

**Comment by HankiDesign** [comment]
No problem, thanks for the quick fix!

**Comment by alexMyG** [comment]
Your VT account has permissions to download reports?
