### ISSUE TITLE
failed to start daemon

### ISSUE THREAD

**Issue by MrChenA** [alexMyG/AndroPyTool#6]
When I use command  `-dr` , I encounter a error like following:
* failed to start daemon *
* failed to start daemon *
error: cannot connect to daemon: Connection refused
error: cannot connect to daemon: Connection refused
error: cannot connect to daemon: Connection refused
Waiting until boot is completed
Boot not completed
error: device '(null)' not found
Boot not completed
error: device '(null)' not found
Boot not completed
error: device '(null)' not found
Boot not completed
error: device offline
Boot not completed
error: device offline

Did I miss something?

**Comment by Earthwater** [comment]
i also got this problem, it seems like "error: device offline" is always something you got when you run androidpytool in docker

**Comment by princenaman** [comment]
Any solution?

**Comment by alexMyG** [comment]
Hi,
I'm sorry for the delay. It is normal. The script is trying to connect to the device but it has not started yet. 
It takes a while (1 or 2 minutes depending on your hardware).
Please, could you try again to see if it connects after several minutes?

**Comment by princenaman** [comment]
Boot not completed
Boot not completed
Boot not completed
Boot not completed
Boot not completed

:cry: waiting for 10 minutes

**Comment by MrChenA** [comment]
> Boot not completed
> Boot not completed
> Boot not completed
> Boot not completed
> Boot not completed
> 
> 😢 waiting for 10 minutes

But All function can be used regularly

**Comment by princenaman** [comment]
Yes, the problem is only with droidbox.
I even tried to run the emulator (GUI) via adb directly and it was stuck on the android boot logo.
So I guess there is some problem with the android-16 sdk maybe?

**Comment by alisolehria** [comment]
Hi,
I am getting the same problem, I have tried to setup droidbox separately too but the emulator just shows a blank screen.

**Comment by mahta643** [comment]
hi
I am getting the same error too.

**Comment by alexMyG** [comment]
It should work now.
