### ISSUE TITLE
Folder not found.

### ISSUE THREAD

**Issue by princenaman** [alexMyG/AndroPyTool#9]
I cannot get it running :(

Either it says folder not found or 0 apks.

![404](https://user-images.githubusercontent.com/6601879/57381118-f5eea880-71c7-11e9-91de-73f17c398852.PNG)

**Comment by alexMyG** [comment]
Hi,
Try this:
docker run --volume=/d/xampp/htdocs/apks/:/apks alexmyg/andropytool -all -s /apks

**Comment by princenaman** [comment]
> 
> 
> Hi,
> Try this:
> docker run --volume=/d/xampp/htdocs/apks/:/apks alexmyg/andropytool -all -s /apks

0 apks still

**Comment by princenaman** [comment]
The problem is with windows 
I got it working on my ubuntu VM
